#!/usr/bin/env python3
"""Build the /go/ tracking pages and the matching QR codes for TCP print collateral.

Iteration: 1

Run from the repo root:   py -3 tools/build-bookmark-assets.py

Writes:
  go/<src>/index.html        one tiny counting-and-redirect page per placement
  assets/qr/<src>.svg        vector QR, for Canva / print
  assets/qr/<src>.png        1200px raster QR, for anything that will not take SVG
  assets/qr/README.md        which code is which

Requires: segno  (py -3 -m pip install segno)
"""

import os
import segno

BASE = "https://theconchparadox.com"

# One entry per placement you want to tell apart in the stats.
# Keep this list SHORT. Every extra code splits the same small number of scans
# into a smaller bucket, and a bucket of four scans tells you nothing.
PLACEMENTS = [
    ("cruise",   "Cruise terminal, taxi stands, terminal-adjacent cafes"),
    ("airport",  "Airport retail and departure hall"),
    ("stores",   "Bookshops and souvenir shops, Aruba"),
    ("hotel",    "Hotel gift shops and concierge desks, Aruba"),
    ("curacao",  "Curacao placements"),
    ("sxm",      "Sint Maarten placements"),
    ("event",    "Signings, talks, conference slides"),
]

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex">
<title>The Conch Paradox</title>
<link rel="canonical" href="{base}/buy.html">
<noscript><meta http-equiv="refresh" content="0;url={base}/buy.html?src={src}"></noscript>
<style>
  body {{ font-family: Georgia, serif; background: #fff; color: #333;
         display: flex; align-items: center; justify-content: center;
         height: 100vh; margin: 0; text-align: center; }}
  a {{ color: #2bbcb6; }}
</style>
</head>
<body>
  <p>Taking you to <em>The Conch Paradox</em>&hellip;<br>
     <a href="{base}/buy.html?src={src}">Continue &rarr;</a></p>
  <script src="{base}/assets/track.js"></script>
  <script>TCPTrack.go({src!r});</script>
</body>
</html>
"""


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    qrdir = os.path.join(root, "assets", "qr")
    os.makedirs(qrdir, exist_ok=True)

    rows = []
    for src, desc in PLACEMENTS:
        url = f"{BASE}/go/{src}"

        # 1. the counting-and-redirect page
        d = os.path.join(root, "go", src)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "index.html"), "w", encoding="utf-8", newline="\n") as f:
            f.write(PAGE.format(base=BASE, src=src))

        # 2. the QR itself.
        # error='h' = 30% redundancy, so the code still scans if the card is
        # scuffed, curled, or partly shadowed on a shop counter. That matters
        # more than code density here: the URL is short enough that even at
        # 'h' this stays a low-version, chunky, easy-to-scan symbol.
        qr = segno.make(url, error="h")
        qr.save(os.path.join(qrdir, f"{src}.svg"), scale=10, border=2,
                dark="#1d3a44", light=None)              # transparent background
        qr.save(os.path.join(qrdir, f"{src}.png"), scale=40, border=2,
                dark="#1d3a44", light="#ffffff")
        rows.append((src, url, desc, qr.version))

    with open(os.path.join(qrdir, "README.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("# TCP bookmark QR codes\n\n")
        f.write("Generated by `tools/build-bookmark-assets.py`. Do not hand-edit.\n\n")
        f.write("Every code points at a `/go/` page that counts the scan and then\n")
        f.write("forwards to `buy.html?src=<code>`. The card is the fixed layer;\n")
        f.write("the buy page is the layer you are free to keep changing.\n\n")
        f.write("| Code | URL | Where it goes | QR version |\n|---|---|---|---|\n")
        for src, url, desc, ver in rows:
            f.write(f"| `{src}` | {url} | {desc} | {ver} |\n")

    print(f"Built {len(rows)} placements.")
    for src, url, _, ver in rows:
        print(f"  {src:9s} -> {url:45s} (QR version {ver})")


if __name__ == "__main__":
    main()
